package com.financeflow.financeflow_backend.entity;

import java.math.BigDecimal;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;


@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Entity // Specifies class as JPA entity
@Table(name = "accounts") // Specifies the name of the table in the database autogenerated by Hibernate
public class Account {
    public enum AccountType {
        SAVINGS,
        DEBIT,
        CREDIT,
    }
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private AccountType accountType;

    @Column(nullable = false)
    private BigDecimal balance;
    private String currency;

    @ManyToOne
    @JoinColumn(name = "user_id", referencedColumnName = "id")
    private User user;

    public String getAccountHolderName(){
        return this.user.getName();
    }

    private void initateAccount(){
        this.balance = new BigDecimal(0);
        this.currency = "CAD";

    }
    public void initiateSavingsAccount(User user){
        initateAccount();
        this.accountType = AccountType.SAVINGS;
        this.user = user;
    }

    public void initiateDebitAccount(User user){
        initateAccount();
        this.accountType = AccountType.DEBIT;
        this.user = user;
    }

    public void initiateCreditAccount(User user){
        initateAccount();
        this.accountType = AccountType.CREDIT;
        this.user = user;
    }

}
