package com.financeflow.financeflow_backend.entity;

import java.math.BigDecimal;
import java.util.List;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;


@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Entity // Specifies class as JPA entity
@Table(name = "accounts") // Specifies the name of the table in the database autogenerated by Hibernate
public class Account {
    public enum AccountType {
        SAVINGS,
        DEBIT,
        CREDIT,
    }
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private AccountType accountType;

    @Column(nullable = false)
    private BigDecimal balance;
    private String currency;

    @OneToMany(cascade = CascadeType.ALL, orphanRemoval = true, fetch = FetchType.LAZY)
    private List<Transaction> transactions;

    public void initiateAccount(){
        this.balance = BigDecimal.ZERO;
        this.currency = "CAD";
    }

    public void initiateSavingsAccount(){
        this.initiateAccount();
        this.accountType = AccountType.SAVINGS;
    }

    public void initiateDebitAccount(){
        this.initiateAccount();
        this.accountType = AccountType.DEBIT;
    }

    public void initiateCreditAccount(){
        this.initiateAccount();
        this.accountType = AccountType.CREDIT;
    }
    public void deposit(BigDecimal amount){
        this.balance = this.balance.add(amount);
    }

    public void withdraw(BigDecimal amount){
        this.balance = this.balance.subtract(amount);
    }

    public void transfer(Account account, BigDecimal amount){
        this.withdraw(amount);
        account.deposit(amount);
    }

    public void addTransaction(Transaction transaction){
        this.transactions.add(transaction);
    }
}
