package com.financeflow.financeflow_backend.entity;

import jakarta.persistence.*;
import lombok.*;

import java.util.ArrayList;
import java.util.List;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Entity // Specifies class as JPA entity
@Table(name = "banks") // Specifies the name of the table in the database autogenerated by Hibernate
public class Bank {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String name;

    @OneToMany(cascade = CascadeType.ALL, orphanRemoval = true, fetch = FetchType.LAZY)
    private List<Account> accounts = new ArrayList<Account>();

    public Bank addAccount(Account account){
        this.accounts.add(account);
        return this;
    }
}
