package com.financeflow.financeflow_backend.entity;
import java.time.LocalDateTime;
import java.math.BigDecimal;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

enum TransactionType {
    DEPOSIT,
    WITHDRAWAL,
    TRANSFER
}

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Entity // Specifies class as JPA entity
@Table(name = "transactions") // Specifies the name of the table in the database autogenerated by Hibernate
public class Transaction {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "account_id", nullable = false)
    private Long accountId;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private TransactionType type;
    @Column(nullable = false)
    private BigDecimal amount;
    private String currency;
    @Column(nullable = false)
    private LocalDateTime date;

    @Column(name = "is_recurring")
    private boolean isRecurring;

    private String description;
    private String category;
}
